apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: narendranreddy/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306 #Target port

