kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql #svc kubectl get svc : mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        app: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: narendranreddy/backend:v1.0
        envFrom:
        - ConfigMapRef:
            name: backend


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #Target port
    

